### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Dai0526** [Dai0526/CUCSSA2017#1]
- [x] Event- 5 html page
- [x] Guests - 2 html page
- [x] Schedule- 2 html page
- [x] Sponsor- 1 html page
- [x] Gallery- 1 html page

- [x] Check All photo Size and quality
- [x] loading logo smaller
- [x] small screen nav size

**Comment by Dai0526** [comment]
Some dynamic request for the web

- [ ]  send email to contact me

- [ ]  send emial to become a partnership
